GET http://localhost:3000/users

###
GET http://localhost:3000/users/localhost:3000/users/stephen_dillane@gameofthron.es

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Xinyi",
    "email" : "OyxYDDD@gmail.com",
    "password" : "xdrjsrhehrjewsdfsdf"
}
###
POST http://localhost:3000/oyxyddd@gmail.com
Content-Type: application/json

{
    "name" : "New Xinyi",
}
###
DELETE POST http://localhost:3000/users/oyxyddd@gmail.com
 